name = "SimulationBasedInference"
uuid = "78927d98-f421-490e-8789-96b006983a5c"
authors = ["Brian Groenke <brian.groenke@awi.de>"]
version = "0.1.0"

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
AffineInvariantMCMC = "a0f608ac-68d0-5108-ad9a-0cdca73324f3"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EnsembleKalmanProcesses = "aa8a2aa5-91d8-4396-bcef-d4f2ec43552d"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
ParameterHandling = "2412ca09-6db7-441c-8e3a-88d5709968c5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJGaussianProcesses = "e2c51686-8c13-4540-892e-18cf079a7e1a"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[extensions]
SimulationBasedInferenceDynamicHMCExt = ["DynamicHMC"]
SimulationBasedInferenceFluxExt = ["Flux"]
SimulationBasedInferenceGenExt = ["Gen"]
SimulationBasedInferenceMLJExt = ["MLJ"]
SimulationBasedInferenceMLJGPExt = ["MLJGaussianProcesses"]
SimulationBasedInferenceTuringExt = ["Turing"]

[compat]
AbstractMCMC = "4"
Bijectors = "0.13"
CommonSolve = "0.2"
ComponentArrays = "0.15"
CondaPkg = "0.2"
DiffEqBase = "5,6"
Distributions = "0.25"
DynamicHMC = "3"
EnsembleKalmanProcesses = "1"
ForwardDiff = "0.10"
LogDensityProblems = "2"
LogDensityProblemsAD = "1"
MCMCChains = "6"
MLJModelInterface = "1"
Optim = "1"
PackageExtensionCompat = "1"
Reexport = "1"
Requires = "1"
SciMLBase = "1,2"
Statistics = "1"
StatsBase = "0.34"
julia = "1.6,1.7,1.8,1.9,1.10"

[extras]
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[targets]
test = ["Gen", "KernelFunctions", "NonlinearSolve", "OrdinaryDiffEq", "Test", "Turing"]
