[deps]
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
EnsembleKalmanProcesses = "aa8a2aa5-91d8-4396-bcef-d4f2ec43552d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SimulationBasedInference = "78927d98-f421-490e-8789-96b006983a5c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
